spring:
  application:
    name: apigateway

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/eureka

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    auth-service:
      path: /auth/**
      service-id: auth-service
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie
#    accounting-service:
#      path: /accounting-service/**
#      service-id: accounting-service